version: '3'
services:
  productapp:
    build: ./app
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
        - "3306"
    volumes:
        - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root
  
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./app:/var/www
    depends_on:
      - productapp

  redis:
    image: redis:alpine
    expose:
      - 6379